### ISSUE TITLE
Make it ngModel (@angular/forms) compliant?

### ISSUE THREAD

**Issue by achimha** [valor-software/ng2-select#232]
The component is not ngModel compliant and cannot easily be used in a form with validation. To make it compliant, it should implement an accessor interface, similar to what is shown here (which is not RC1 compatible): http://restlet.com/blog/2016/02/17/implementing-angular2-forms-beyond-basics-part-2/

Are there plans to make it compatible?

**Comment by Namek** [comment]
To be more specific, rather look at this link: http://almerosteyn.com/2016/04/linkup-custom-control-to-ngcontrol-ngmodel It's shorter and narrowed down to the topic.

The job is to extend `SelectComponent` with [ControlValueAccessor interface](https://github.com/angular/angular/blob/master/modules/%40angular/common/src/forms/directives/control_value_accessor.ts) implementation.

It's basically a matter of implementing those methods in there:

``` ts
writeValue(obj: any): void {
  // set selected values
}

registerOnChange(fn: any): void {
  // simply save callback which will be called when `selected` changes
}

registerOnTouched(fn: any): void {
  // save a callback which will be called when control is touched (clicked)
}
```

@valorkin I'll make the PR but it would be useful to have #223 merged in.

**Comment by Namek** [comment]
Here's my branch to be PR-ed: [development---set_selected_items/feat---control_value_accessor/feat](https://github.com/Namek/ng2-select/tree/development---set_selected_items/feat---control_value_accessor/feat) - it's based on #223.

**Comment by valorkin** [comment]
actually there are plans to make in compliant with NgModel and NgControl

**Comment by Namek** [comment]
and what about my branch? Isn't that enough?

**Comment by kamikaze** [comment]
I've got a problem because of that. Any progress?

**Comment by jasonroyle** [comment]
I need a way of two way data binding due to the ng-select directive being part of a form that is loaded in a child route where the parent route contains an ID parameter. Whenever the parent route's ID parameter changes the selected items of the ng-select directive should update accordingly though nothing I have tried accomplishes this.

The documentation seems to suggest `[data]="selectedItems"` should work but this is not the case, the only way I can get ng-select to load data is by using `[initData]="selectedItems"` but that only works once and doesn't listen for changes.

The only way I could think is to force the form's component to disallow reuse but that's dirty!

**Comment by yabab-dev** [comment]
Hi,

I've made this component ngModel compliant with few lines of codes here : https://github.com/chymz/ng2-select/commit/0b79ec583b8f5de763728fdee9550fb0641077de

It seems to work perfectly with the last RC4

[Edit] Here is a pull request : https://github.com/valor-software/ng2-select/pull/299

**Comment by valorkin** [comment]
at the moment I am updating and publishing ng2-bootstrap, after it I will get here

**Comment by kamikaze** [comment]
please make it tslint compatible too :)

**Comment by 0cv** [comment]
You may want to consider to make it compliant with formControlName too. Even more important since ngModel seems now to be considered in the new forms as an edge case (i.e. ngModel is intended for standalone input while formControlName is the real control part of a form). https://docs.google.com/document/u/0/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub

**Comment by yabab-dev** [comment]
Well, my pull request make this component compatible with template-driven forms (ngModel) and model-driven forms too (formGroup/formControlName)

**Comment by 0cv** [comment]
Little is happening... Any chance to have that reviewed/merged/released?

**Comment by ghost** [comment]
Add my vote, ngModule is a must, otherwise all the cool stuff of Angular are worthless. Thanks :)

**Comment by k1ng440** [comment]
+1

**Comment by valorkin** [comment]
can you try typeahead from ng2-bootstrap?

**Comment by elmartino** [comment]
+1

**Comment by christianecker** [comment]
+1

**Comment by sveatlo** [comment]
+1

**Comment by lanceschi** [comment]
👍

**Comment by yairgo** [comment]
Any movement on this at all?

**Comment by toke182** [comment]
+1

**Comment by toke182** [comment]
Fix in https://github.com/valor-software/ng2-select/pull/575

**Comment by Avien** [comment]
After upgrading to latest version, I'm trying to subscribe to the form valueChanges observable to be notified when the ng2-select selected value has changed

```this.form.first.control.valueChanges.subscribe(data=> { ...```

Why isnt it working if its compliant with forms?

**Comment by blubberbo** [comment]
@toke182 so is this compliant with angular 2 forms validation? I'm sorry, I didn't quite understand

**Comment by toke182** [comment]
@blubberbo Yes, It got merged to development branch some time ago

**Comment by blubberbo** [comment]
@toke182 is there an example of an implementation somewhere I could take a look at maybe?

**Comment by BBaysinger** [comment]
This feature would be greatly appreciated.

**Comment by michelebombardi** [comment]
Yes, it would be greatly appreciated!

**Comment by bryanbanda** [comment]
Just checking here, just tried to bind to ngModel and getting an error that it's not a property of select2. Was any progress made on making this component ngModel compliant?

**Comment by bassrock** [comment]
ng2-select-compat seems to be ngModel complaint but I keep getting the following error when there are more then 1 ng-select on one page, the first ng-select on the page works. All the subsequent ones do not.:

```
ERROR TypeError: selectedItems.map is not a function
    at SelectComponent.set [as active] (http://localhost:4200/vendor.bundle.js:52879:46)
    at SelectComponent.webpackJsonp.../../../../ng2-select-compat/select/select.js.SelectComponent.writeValue (http://localhost:4200/vendor.bundle.js:53024:21)
    at http://localhost:4200/vendor.bundle.js:143067:29
    at http://localhost:4200/vendor.bundle.js:144253:65
    at Array.forEach (<anonymous>)
    at FormControl.webpackJsonp.../../../forms/@angular/forms.es5.js.FormControl.setValue (http://localhost:4200/vendor.bundle.js:144253:28)
    at FormGroupDirective.webpackJsonp.../../../forms/@angular/forms.es5.js.FormGroupDirective.updateModel (http://localhost:4200/vendor.bundle.js:146081:14)
    at FormControlName.webpackJsonp.../../../forms/@angular/forms.es5.js.FormControlName.ngOnChanges (http://localhost:4200/vendor.bundle.js:146530:32)
    at checkAndUpdateDirectiveInline (http://localhost:4200/vendor.bundle.js:137306:19)
    at checkAndUpdateNodeInline (http://localhost:4200/vendor.bundle.js:138797:17)
```

**Comment by optimistex** [comment]
New life the component is there: https://github.com/optimistex/ng2-select-ex

**Comment by varnastadeus** [comment]
you could try https://github.com/ng-select/ng-select, it has this and many more features implemented.

**Comment by RamenSayami** [comment]
+1
