### ISSUE TITLE
FormControl - setValue or patchValue exception

### ISSUE THREAD

**Issue by mkndn** [valor-software/ng2-select#621]
I am using the version 1.2.0 and i hope now this control support ngmodel and hopefully the formControlName in case of Model-Driven forms.

I have added the **formControlName='group'** to the **ng-select** in html

I was actually using the following code to set the control value dynamically,
`this.groupForm.controls['group'].patchValue(data, { onlySelf:true });`
but i am getting the following exception

`TypeError: selectedItems.map is not a function
    at SelectComponent.set [as active] (http://localhost:3000/node_modules/ng2-select/select/select.js:83:46)
    at SelectComponent.writeValue (http://localhost:3000/node_modules/ng2-select/select/select.js:228:21)
    at eval (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:1637:31)
    at eval (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:2931:69)
    at Array.forEach (native)
    at FormControl.setValue (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:2931:32)
    at FormControl.patchValue (http://localhost:3000/node_modules/@angular/forms/bundles/forms.umd.js:2947:18)
    at RegisterComponent.onGroupSelect (http://localhost:3000/app/assets/js/register/register.component.js:185:14)
    at View_RegisterComponent2.handleEvent_3 (/LoginModule/RegisterComponent/component.ngfactory.js:148:45)
    at View_RegisterComponent2.eval (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12774:41)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4116:40)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.next (http://localhost:3000/node_modules/rxjs/Subscriber.js:172:22)
    at Subscriber._next (http://localhost:3000/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (http://localhost:3000/node_modules/rxjs/Subscriber.js:89:18)`

**Comment by mkndn** [comment]
My Bad. I fixed it myself. I made mistake here
`this.groupForm.controls['group'].patchValue(data, { onlySelf:true });`

Here data is not of type Array, hence the error.  I changed it to an Array something like 
`this.selectedGroup = [];`
`this.selectedGroup.push (JSON.parse(data));`
`this.groupForm.controls['group'].patchValue(this.selectedGroup, { onlySelf:true });`
and voila the error disappeared.
