### ISSUE TITLE
Build npm package

### ISSUE THREAD

**Issue by mfonolleda** [valor-software/ng2-select#679]
Hi All, I've made an update to the repo to make it work with async api calls as explained [here](https://github.com/valor-software/ng2-select/issues/635#issuecomment-281094377). Basically, it consists in changing the method   `public open():void {` as `private open():void {` so that it can be called to force the dropdown to open when `items` is updated after an async api call.

However, I am at a loss about how to re-build the npm package. I have tried cloning the repo, making the code edits and then executing `npm install` and then `ng build` but the build throws errors.

Any help on the correct process to re-build the package after updating the code is much appreciated!

Thanks, - MF

**Comment by mfonolleda** [comment]
Update: 
I have tried running `npm run build` after installing the `ngm` package. However, it throws the error:

```
> ng2-select-base@1.2.0 build /home/miquel/workspace/ng2-select-valor
> ngm build -p src --clean

[11:58:48] Clean dist folders [started]
[11:58:48] Cleaning dist [started]
[11:58:48] Cleaning dist [completed]
[11:58:48] Clean dist folders [completed]
[11:58:48] Copy md files and license [started]
[11:58:48] Copy md files and license [completed]
[11:58:48] Build package.json files [started]
[11:58:48] Build package.json files [completed]
[11:58:48] Build projects [started]
[11:58:48] Building ng2-select (src) [started]
[11:58:54] Building ng2-select (src) [failed]
[11:58:54] Build projects [failed]

Command failed: ngc -p src
Error at /home/miquel/workspace/ng2-select-valor/scripts/typings.d.ts:11:15: Cannot redeclare block-scoped variable 'global'.
Error at /home/miquel/workspace/ng2-select-valor/node_modules/@types/node/index.d.ts:49:13: Cannot redeclare block-scoped variable 'global'
```

**Comment by mfonolleda** [comment]
After further analysis, there is not need to rebuild the package to call the open() method. 

Therefore, I have no need to rebuild the package anymore and close this issue.
