### ISSUE TITLE
Uncaught TypeError: ctorParameters.map is not a function at ReflectionCapabilities.parameters

### ISSUE THREAD

**Issue by andrescala** [valor-software/ng2-select#713]
I got this error...

Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters

**Full error:**
Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:41924:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:42058:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:24029:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:23994:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:23769:28)
    at http://localhost:4200/main.bundle.js:23838:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:23831:44)
    at http://localhost:4200/main.bundle.js:23819:50
    at Array.forEach (native)

This is part of my package.json
"dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "@types/jasmine": "^2.5.45",
    "angular2-flash-messages": "^1.0.5",
    "angular2-jwt": "^0.1.28",
    "animate.css": "3.1.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.0",
    "metismenu": "^2.5.0",
    "ng2-select": "^1.2.0",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  }

Any idea to solve it?

**Comment by christopheInteractiv** [comment]
just upgade angular core to 2.4
see this post : http://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl
