### ISSUE TITLE
Error on Angular Universal

### ISSUE THREAD

**Issue by eluizbr** [valor-software/ng2-select#831]
Hi,
I'm try use ng2-select with Angular Universal, and received this error:

`
/Users/eluizbr/Desktop/projetos/Lab3DVLP/busqlog/newPortal/node_modules/ng2-select-compat/select/off-click.js:39
    __metadata("design:paramtypes", [MouseEvent]),
                                     ^
ReferenceError: MouseEvent is not defined
    at Object.<anonymous> (/Users/eluizbr/Desktop/projetos/Lab3DVLP/busqlog/newPortal/node_modules/ng2-select-compat/select/off-click.js:39:38)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
`

Any tip?

Thanks.

**Comment by anas3636** [comment]
I have the same Issue !!!

**Comment by simonmlewis** [comment]
It is being tracked here:
https://github.com/valor-software/ng2-select/issues/258
